name: Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
         
      - name: Setup mongodb with password
        uses: getong/mongo-action@v1.1
        with:
          # Version of mongo to use
          mongo version: '4.2-bionic'
          # The port of host
          host port: 27017
          # The username of the mongo
          mongo username: 'dbUser'
          # The password of the mongo
          mongo password: 'dbPass'
          
      - name: Run npm install
        run: npm install
      - name: Run Test
        run: npm run test
