name: Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
        mongodb-version: [4.0, 4.2]

    steps:
      - uses: actions/checkout@v1
      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
         
      - name: Setup and start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          # MongoDB version to use (default "latest")
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Run npm install
        run: npm install
        
      - name: Run Test
        run: npm run test
